name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: true

      # see https://docs.mongodb.com/mongoid/current/tutorials/mongoid-installation/ for supported versions
      matrix:
        ruby_version: ['3.1', '3.0', '2.7', '2.6', '2.5']
        mongoid_version: [head, '7.3', '7.2', '7.1', '7.0', '6.4']

        exclude:
          - ruby_version: '3.1'
            mongoid_version: '7.0'
          - ruby_version: '3.1'
            mongoid_version: '6.4'

          - ruby_version: '3.0'
            mongoid_version: '7.0'
          - ruby_version: '3.0'
            mongoid_version: '6.4'

          - ruby_version: '2.7'
            mongoid_version: '6.4'

        include:
          - ruby_version: '2.5'
            mongoid_version: '6.3'
          - ruby_version: '2.5'
            mongoid_version: '6.2'

          - ruby_version: '2.4'
            mongoid_version: '6.1'

          - ruby_version: '2.3'
            mongoid_version: '6.0'
          - ruby_version: '2.3'
            mongoid_version: '5.4'
            bundler_version: '1'

          - ruby_version: '2.2'
            mongoid_version: '5.2'
          - ruby_version: '2.2'
            mongoid_version: '5.1'

          - ruby_version: '2.1'
            mongoid_version: '5.0'
          - ruby_version: '2.1'
            mongoid_version: '4.0'

    env:
      MONGOID_VERSION: ${{ matrix.mongoid_version }}

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          bundler: ${{ matrix.bundler_version || 'latest' }}
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - uses: supercharge/mongodb-github-action@1.7.0

      - run: bundle exec rake
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
